# -*- coding: utf-8 -*-
"""mushroom_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDDW4hIYQcZwOjP3Uwgr0ywgBjoHBm4p
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = pd.read_csv("mushrooms.csv") #we load the dataset

print("First five rows:\n")
print(data.head())

print("\nDataset shape:", data.shape)

#this is to convert every column from letters to numbers
encoders = {}

for column in data.columns:
    encoder = LabelEncoder()
    data[column] = encoder.fit_transform(data[column])
    encoders[column] = encoder

#features and labels
X = data.drop("class", axis=1)
y = data["class"]

#splitting the data..
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=7,
    shuffle=True
)

#training the model
model = DecisionTreeClassifier(
    max_depth=6,
    random_state=7
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

#evaluation
accuracy = accuracy_score(y_test, predictions)

print("\nAccuracy:", round(accuracy * 100, 2), "%")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))

print("\nClassification Report:")
print(classification_report(y_test, predictions))

#show us the most important features
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values("Importance", ascending=False)

print("\nMost important features:\n")
print(importance.head(10))

#example prediction
sample = X.iloc[[0]]

prediction = model.predict(sample)[0]

if prediction == 1:
    print("\nPrediction: Edible")
else:
    print("\nPrediction: Poisonous")